#!/usr/bin/perl

my $code = $ENV{'MATROID_CODE'};
my $logs = $ENV{'MATROID_LOGS'};

for(my $i=80+26; $i>26; $i--) {
`python $code/get_pair_data.py $i 5 < $logs/by_ray_id/n5_vary${i}_output > $code/choose_axioms/by_rays_id/n5_vary$i`;
}
