#!/usr/bin/perl

# Alter slicer.c by adding a number to the fixed axiom list

use strict;

my $ADDN = $ARGV[0];

while(<STDIN>) {
	if(/^(\s*#define\s+FIX_AXIOMS\s+)([0-9]+)/) { print $1 . ($2 + 1). "\n"; }
	elsif(/^(\s*#define\s+FIX_AXIOMS_AVAIL\s+)([0-9]+)/) { print $1 . ($2 + 1). "\n"; }
	elsif(/^(\s*int\s+fixed_axioms\[FIX_AXIOMS_AVAIL\] = \{[^\}]+)(.*)$/) {
           print $1 . ", ".  $ADDN . $2 . "\n";
        }else{print;}
}