#!/usr/bin/perl

# From the outputs of get_pair_data.py, create a summary of the experiments
# Usage: ./create_summary 4|5|6 "<selected axioms>"

use strict;

my $SET_N = $ARGV[0];
my @FIXED_AXIOMS = split(/,\s*/, $ARGV[1]);

print "SET_N=$SET_N FIXED_AXIOMS=".join(',', @FIXED_AXIOMS)."\n";

